export const usersData = [
	{
		id: "1",
		name: "John Doe",
		email: "johndoe@gmail.com",
		age: 32,
		attendingMeeting: false,
		profession: "Software Engineer",
		maritalStatus: "Single",
		address: "123 Main Street, Cityville",
		phoneNumber: "555-123-4567",
		emergencyContact: {
			name: "Jane Smith",
			relationship: "Friend",
			phoneNumber: "555-987-6543",
		},
		medicalHistory: "No significant medical history.",
		mentalHealthHistory: "Previously diagnosed with anxiety disorder.",
		goalsAndObjectives: "Improve stress management and work-life balance.",
		preferredPronouns: "He/Him",
		preferredTherapist: "No preference",
		insuranceInformation: {
			provider: "XYZ Insurance",
			policyNumber: "POL123456",
			requirements: "Reimbursement required.",
		},
	},
	{
		id: "2",
		name: "Alice Johnson",
		email: "alice.johnson@example.com",
		age: 28,
		attendingMeeting: false,
		profession: "Teacher",
		maritalStatus: "Married",
		address: "456 Oak Avenue, Townsville",
		phoneNumber: "555-789-0123",
		emergencyContact: {
			name: "Bob Johnson",
			relationship: "Spouse",
			phoneNumber: "555-321-6548",
		},
		medicalHistory: "Allergic to peanuts.",
		mentalHealthHistory: "First-time therapy seeker.",
		goalsAndObjectives: "Manage stress related to work and personal life.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Open to recommendations",
		insuranceInformation: null, // No insurance coverage.
	},
	{
		id: "3",
		name: "Michael Smith",
		email: "michael.smith@example.com",
		age: 40,
		attendingMeeting: false,
		profession: "Psychologist",
		maritalStatus: "Married",
		address: "789 Elm Street, Villagetown",
		phoneNumber: "555-555-5555",
		emergencyContact: {
			name: "Sarah Smith",
			relationship: "Spouse",
			phoneNumber: "555-555-5556",
		},
		medicalHistory: "High blood pressure.",
		mentalHealthHistory: "Experienced depression in the past.",
		goalsAndObjectives: "Maintain work-life balance and reduce stress.",
		preferredPronouns: "He/Him",
		preferredTherapist: "Self",
		insuranceInformation: {
			provider: "ABC Insurance",
			policyNumber: "POL789012",
			requirements: "Direct billing available.",
		},
	},
	{
		id: "4",
		name: "Emily Brown",
		email: "emily.brown@example.com",
		age: 35,
		attendingMeeting: false,
		profession: "Social Worker",
		maritalStatus: "Divorced",
		address: "567 Maple Lane, Suburbia",
		phoneNumber: "555-987-6543",
		emergencyContact: {
			name: "Olivia Brown",
			relationship: "Sister",
			phoneNumber: "555-123-4567",
		},
		medicalHistory: "Asthma.",
		mentalHealthHistory: "Grief and loss due to divorce.",
		goalsAndObjectives: "Coping with life changes and stress.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Experienced therapist",
		insuranceInformation: {
			provider: "DEF Insurance",
			policyNumber: "POL456789",
			requirements: "Pre-authorization needed.",
		},
	},
	{
		id: "5",
		name: "David Wilson",
		email: "david.wilson@example.com",
		age: 45,
		attendingMeeting: false,
		profession: "Accountant",
		maritalStatus: "Married",
		address: "101 Pine Street, Metroville",
		phoneNumber: "555-222-3333",
		emergencyContact: {
			name: "Lisa Wilson",
			relationship: "Spouse",
			phoneNumber: "555-333-4444",
		},
		medicalHistory: "Type 2 diabetes.",
		mentalHealthHistory: "Stress due to work pressure.",
		goalsAndObjectives: "Manage diabetes and reduce work-related stress.",
		preferredPronouns: "He/Him",
		preferredTherapist: "Cognitive-Behavioral Therapist",
		insuranceInformation: {
			provider: "GHI Insurance",
			policyNumber: "POL555666",
			requirements: "Co-payment required.",
		},
	},
	{
		id: "6",
		name: "Sophia Lee",
		email: "sophia.lee@example.com",
		age: 29,
		attendingMeeting: false,
		profession: "Graphic Designer",
		maritalStatus: "Single",
		address: "222 Oak Street, Artville",
		phoneNumber: "555-777-8888",
		emergencyContact: {
			name: "Lucas Lee",
			relationship: "Brother",
			phoneNumber: "555-999-0000",
		},
		medicalHistory: "None.",
		mentalHealthHistory: "Stress and anxiety related to work.",
		goalsAndObjectives: "Manage stress and enhance creativity.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Art Therapist",
		insuranceInformation: null, // No insurance coverage.
	},
	{
		id: "7",
		name: "Daniel Taylor",
		email: "daniel.taylor@example.com",
		age: 50,
		attendingMeeting: false,
		profession: "Retired",
		maritalStatus: "Widowed",
		address: "321 Birch Road, Quietville",
		phoneNumber: "555-444-5555",
		emergencyContact: {
			name: "Sophie Taylor",
			relationship: "Daughter",
			phoneNumber: "555-444-6666",
		},
		medicalHistory: "Heart condition.",
		mentalHealthHistory: "Grief and loneliness after losing spouse.",
		goalsAndObjectives: "Coping with loss and finding purpose.",
		preferredPronouns: "He/Him",
		preferredTherapist: "Experienced grief counselor",
		insuranceInformation: {
			provider: "JKL Insurance",
			policyNumber: "POL777888",
			requirements: "Limited sessions covered.",
		},
	},
	{
		id: "8",
		name: "Ella Martinez",
		email: "ella.martinez@example.com",
		age: 38,
		attendingMeeting: false,
		profession: "Nurse",
		maritalStatus: "Married",
		address: "789 Cedar Lane, Healthville",
		phoneNumber: "555-666-7777",
		emergencyContact: {
			name: "Carlos Martinez",
			relationship: "Spouse",
			phoneNumber: "555-666-8888",
		},
		medicalHistory: "Allergic to shellfish.",
		mentalHealthHistory: "Burnout and stress from healthcare work.",
		goalsAndObjectives: "Reduce stress and avoid burnout.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Therapist with healthcare experience",
		insuranceInformation: {
			provider: "MNO Insurance",
			policyNumber: "POL888999",
			requirements: "Direct billing available.",
		},
	},
	{
		id: "9",
		name: "William Adams",
		email: "william.adams@example.com",
		age: 27,
		attendingMeeting: false,
		profession: "Student",
		maritalStatus: "Single",
		address: "456 Pine Avenue, Campusville",
		phoneNumber: "555-111-2222",
		emergencyContact: {
			name: "Mary Adams",
			relationship: "Parent",
			phoneNumber: "555-111-3333",
		},
		medicalHistory: "None.",
		mentalHealthHistory: "Academic stress and anxiety.",
		goalsAndObjectives: "Academic success and stress management.",
		preferredPronouns: "He/Him",
		preferredTherapist: "Student Counselor",
		insuranceInformation: null, // No insurance coverage.
	},
	{
		id: "10",
		name: "Olivia Rodriguez",
		email: "olivia.rodriguez@example.com",
		age: 22,
		attendingMeeting: false,
		profession: "Artist",
		maritalStatus: "Single",
		address: "987 Willow Lane, Creativityville",
		phoneNumber: "555-999-1111",
		emergencyContact: {
			name: "Diego Rodriguez",
			relationship: "Sibling",
			phoneNumber: "555-999-2222",
		},
		medicalHistory: "None.",
		mentalHealthHistory: "Creative block and self-doubt.",
		goalsAndObjectives: "Overcome creative block and boost self-esteem.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Art Therapist",
		insuranceInformation: null, // No insurance coverage.
	},
];
