export const usersData = [
	{
		id: "xxw-ws-wdd",
		name: "Subham Mishra",
		role: "coach",
		email: "cet.subham@gmail.com",
	},
	{
		id: "1",
		name: "John Doe",
		email: "johndoe@gmail.com",
		age: 32,
		profession: "Software Engineer",
		maritalStatus: "Single",
		address: "123 Main Street, Cityville",
		phoneNumber: "555-123-4567",
		medicalHistory: "No significant medical history.",
		mentalHealthHistory: "Previously diagnosed with anxiety disorder.",
		goalsAndObjectives: "Improve stress management and work-life balance.",
		preferredPronouns: "He/Him",
		preferredTherapist: "No preference",
	},
	{
		id: "2",
		name: "Alice Johnson",
		email: "alice.johnson@example.com",
		age: 28,
		profession: "Teacher",
		maritalStatus: "Married",
		address: "456 Oak Avenue, Townsville",
		phoneNumber: "555-789-0123",
		medicalHistory: "Allergic to peanuts.",
		mentalHealthHistory: "First-time therapy seeker.",
		goalsAndObjectives: "Manage stress related to work and personal life.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Open to recommendations",
	},
	{
		id: "3",
		name: "Michael Smith",
		email: "michael.smith@example.com",
		age: 40,
		profession: "Psychologist",
		maritalStatus: "Married",
		address: "789 Elm Street, Villagetown",
		phoneNumber: "555-555-5555",
		medicalHistory: "High blood pressure.",
		mentalHealthHistory: "Experienced depression in the past.",
		goalsAndObjectives: "Maintain work-life balance and reduce stress.",
		preferredPronouns: "He/Him",
		preferredTherapist: "Self",
	},
	{
		id: "4",
		name: "Emily Brown",
		email: "emily.brown@example.com",
		age: 35,
		profession: "Social Worker",
		maritalStatus: "Divorced",
		address: "567 Maple Lane, Suburbia",
		phoneNumber: "555-987-6543",
		medicalHistory: "Asthma.",
		mentalHealthHistory: "Grief and loss due to divorce.",
		goalsAndObjectives: "Coping with life changes and stress.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Experienced therapist",
	},
	{
		id: "5",
		name: "David Wilson",
		email: "david.wilson@example.com",
		age: 45,
		profession: "Accountant",
		maritalStatus: "Married",
		address: "101 Pine Street, Metroville",
		phoneNumber: "555-222-3333",
		medicalHistory: "Type 2 diabetes.",
		mentalHealthHistory: "Stress due to work pressure.",
		goalsAndObjectives: "Manage diabetes and reduce work-related stress.",
		preferredPronouns: "He/Him",
		preferredTherapist: "Cognitive-Behavioral Therapist",
	},
	{
		id: "6",
		name: "Sophia Lee",
		email: "sophia.lee@example.com",
		age: 29,
		profession: "Graphic Designer",
		maritalStatus: "Single",
		address: "222 Oak Street, Artville",
		phoneNumber: "555-777-8888",
		medicalHistory: "None.",
		mentalHealthHistory: "Stress and anxiety related to work.",
		goalsAndObjectives: "Manage stress and enhance creativity.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Art Therapist",
	},
	{
		id: "7",
		name: "Daniel Taylor",
		email: "daniel.taylor@example.com",
		age: 50,
		profession: "Retired",
		maritalStatus: "Widowed",
		address: "321 Birch Road, Quietville",
		phoneNumber: "555-444-5555",
		medicalHistory: "Heart condition.",
		mentalHealthHistory: "Grief and loneliness after losing spouse.",
		goalsAndObjectives: "Coping with loss and finding purpose.",
		preferredPronouns: "He/Him",
		preferredTherapist: "Experienced grief counselor",
	},
	{
		id: "8",
		name: "Ella Martinez",
		email: "ella.martinez@example.com",
		age: 38,
		profession: "Nurse",
		maritalStatus: "Married",
		address: "789 Cedar Lane, Healthville",
		phoneNumber: "555-666-7777",
		medicalHistory: "Allergic to shellfish.",
		mentalHealthHistory: "Burnout and stress from healthcare work.",
		goalsAndObjectives: "Reduce stress and avoid burnout.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Therapist with healthcare experience",
	},
	{
		id: "9",
		name: "William Adams",
		email: "william.adams@example.com",
		age: 27,
		profession: "Student",
		maritalStatus: "Single",
		address: "456 Pine Avenue, Campusville",
		phoneNumber: "555-111-2222",
		medicalHistory: "None.",
		mentalHealthHistory: "Academic stress and anxiety.",
		goalsAndObjectives: "Academic success and stress management.",
		preferredPronouns: "He/Him",
		preferredTherapist: "Student Counselor",
	},
	{
		id: "10",
		name: "Olivia Rodriguez",
		email: "olivia.rodriguez@example.com",
		age: 22,
		profession: "Artist",
		maritalStatus: "Single",
		address: "987 Willow Lane, Creativityville",
		phoneNumber: "555-999-1111",
		medicalHistory: "None.",
		mentalHealthHistory: "Creative block and self-doubt.",
		goalsAndObjectives: "Overcome creative block and boost self-esteem.",
		preferredPronouns: "She/Her",
		preferredTherapist: "Art Therapist",
	},
];
